#!/usr/lib/R/bin/Rscript

library(lme4)


names=names(Beta_HalleFall2006)
HalleFall2006_trimmed=HalleFall2006[,names]
HalleFall2006_trimmed=cbind(HalleFall2006[,1:14],HalleFall2006_trimmed)


HalleFall2006_trimmedfolds=createFolds(rownames(HalleFall2006_trimmed),10)


R2_pred=c()
R2_exp=c()

for (i in unique(HalleFall2006_trimmedfolds)){


	Validation_Set=HalleFall2006_trimmed[i,]
	Training_Set=HalleFall2006_trimmed[-i,]
	DTB_Valid=HalleFall2006_trimmed[i,"DTB"] #Validation set
	DTB_Train=HalleFall2006_trimmed[-i,"DTB"] #Training set


	model=lm(DTB~.,data=Training_Set[,-c(1:3,5:14)])
	na_omitted_names=names((na.omit(model$coefficients)))
	na_omitted_names=na_omitted_names[-1] # To remove the Intercept name
	na_omitted_names=str_replace_all(na_omitted_names, "`","")
	
	
	Training_Set=cbind(Training_Set[,1:14],Training_Set[,na_omitted_names])
	Validation_Set=cbind(Validation_Set[,1:14], Validation_Set[,na_omitted_names])
	model=lm(DTB~.,data=Training_Set[,-c(1:3,5:14)])
	
	## Explanatory
	exp=predict(model,newx=Training_Set[,-c(1:3,5:14)])
	correlation_exp=cor(exp,DTB_Train)
	R2_exp=c(R2_exp,correlation_exp)
	
	## Predictive

	pred=predict(model,newdata=Validation_Set[,-c(1:3,5:14)])
	correlation_pred=cor(pred,DTB_Valid)
	R2_pred=c(R2_pred,correlation_pred)

}

save(model,R2_pred,R2_exp,file=".RData")
